#!/usr/bin/env python3
# -*- coding: utf-8 -*-


prefix = "."
stop-words = "lemur-stopwords.txt"

dataset = "book_titles"
corpus = "line.toml"
index = "idx_titles"

duplicates = 'True'

query-judgements = "book_title_qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"


[ranker]
method = "bm25"
k1 = 1.2
b = 0.5
k3 = 500

[query-runner]
query-path = "goodreads_book_series_queries.txt"
query-id-start = 0